name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 7.0.0-dev
homepage: https://github.com/fluttercandies/extended_image

environment:
  sdk: '>=2.18.0-36.0.dev <3.0.0'

dependencies:
  extended_image_library: ^4.0.0-dev
  flutter:
    sdk: flutter
  meta: ^1.7.0
